'use strict';
const chapters=window.REVIEW_CHAPTERS;
const themeButton=document.getElementById('theme-toggle');
function setThemeLabel(){const light=document.documentElement.dataset.theme==='light';const label=`Switch to ${light?'dark':'light'} mode`;themeButton.setAttribute('aria-label',label);themeButton.title=label;document.querySelector('meta[name="theme-color"]').content=light?'#f7f7f9':'#090a0c'}
themeButton.addEventListener('click',()=>{document.documentElement.dataset.theme=document.documentElement.dataset.theme==='dark'?'light':'dark';try{localStorage.setItem('patoo-theme',document.documentElement.dataset.theme)}catch{}setThemeLabel()});setThemeLabel();
function node(tag,className,text){const e=document.createElement(tag);if(className)e.className=className;if(text!==undefined)e.textContent=text;return e}
const nav=document.getElementById('chapter-nav');const search=document.getElementById('note-search');const header=document.getElementById('chapter-header');const list=document.getElementById('notes-list');const chapterAliases={misc:'forensics',osint:'forensics'};function chapterFromHash(){const hash=location.hash.slice(1);return chapterAliases[hash]||hash}let active=chapters.some(c=>c.id===chapterFromHash())?chapterFromHash():'setup';let toastTimer;
function toast(message){const e=document.getElementById('lab-toast');e.textContent=message;e.hidden=false;clearTimeout(toastTimer);toastTimer=setTimeout(()=>e.hidden=true,3500)}
chapters.forEach((chapter,index)=>{const button=node('button','chapter-button');button.type='button';button.dataset.chapter=chapter.id;button.append(node('span','chapter-number',String(index).padStart(2,'0')),node('span','',chapter.label),node('span','chapter-count',String(chapter.notes.length)));button.addEventListener('click',()=>{search.value='';active=chapter.id;history.replaceState(null,'',`#${active}`);render();header.scrollIntoView({block:"start"})});nav.append(button)});
function codePanel(block){const panel=node('div','code-panel');const bar=node('div','code-header');const copy=node('button','copy-button','Copy');copy.type='button';copy.setAttribute('aria-label',`Copy ${block.label}`);copy.addEventListener('click',async()=>{try{await navigator.clipboard.writeText(block.code);copy.textContent='Copied';setTimeout(()=>copy.textContent='Copy',1800)}catch{toast('Select the code and copy it manually.')}});bar.append(node('span','',block.label));if(block.copyable!==false)bar.append(copy);const pre=node('pre');pre.append(node('code','',block.code));panel.append(bar,pre);return panel}
function noteCard(note,index,chapter){const card=node('article','note-card');card.id=note.id;const title=node('div','note-heading');title.append(node('span','note-step',String(index+1).padStart(2,'0')),node('h3','',note.title));card.append(title,node('p','note-lead',note.lead));if(search.value.trim())card.append(node('p','chapter-kicker',chapter.label));if(note.steps?.length){const steps=node('ol','note-steps');note.steps.forEach(step=>steps.append(node('li','',step)));card.append(steps)}for(const block of note.blocks||[]){card.append(codePanel(block));if(block.explanation)card.append(node('p','code-explanation',block.explanation))}if(note.look){const callout=node('div','note-callout');callout.append(node('strong','','What to look for'),node('p','',note.look));card.append(callout)}if(note.pitfalls?.length){const pitfalls=node('div','pitfalls');pitfalls.append(node('strong','','Common traps'));const items=node('ul');note.pitfalls.forEach(item=>items.append(node('li','',item)));pitfalls.append(items);card.append(pitfalls)}if(note.answer){const details=node('details','drill-answer');details.append(node('summary','','Reveal the practice explanation'),node('p','',note.answer));card.append(details)}if(note.sources?.length){const refs=node('div','note-sources');refs.append(node('span','','References'));note.sources.forEach(([label,url])=>{const link=node('a','',label);link.href=url;link.target='_blank';link.rel='noopener noreferrer';refs.append(link)});card.append(refs)}return card}
function render(){const query=search.value.trim().toLowerCase();const selected=chapters.find(c=>c.id===active);nav.querySelectorAll('button').forEach(button=>{const chosen=!query&&button.dataset.chapter===active;button.classList.toggle('selected',chosen);button.setAttribute('aria-pressed',String(chosen))});header.replaceChildren();const heading=node('div','chapter-heading');heading.append(node('p','chapter-kicker',query?'SEARCH RESULTS':selected.kind),node('h2','',query?`Results for “${search.value.trim()}”`:selected.title),node('p','',query?'Search across every chapter. Clear the search to return to your selected chapter.':selected.intro));header.append(heading);if(!query&&selected.workspace){header.append(codePanel(selected.workspace),node('p','code-explanation',selected.workspace.explanation))}list.replaceChildren();let count=0;for(const chapter of chapters){if(!query&&chapter.id!==active)continue;for(const note of chapter.notes){if(query&&!JSON.stringify(note).toLowerCase().includes(query))continue;list.append(noteCard(note,count++,chapter))}}if(count===0)list.append(node('p','empty-notes',query?'No matching notes. Try a tool name or a shorter phrase.':'Notes are being prepared.'));document.getElementById('search-status').textContent=`${count} review note${count===1?'':'s'} shown.`;}
search.addEventListener('input',render);window.addEventListener('hashchange',()=>{const id=chapterFromHash();if(chapters.some(c=>c.id===id)){active=id;search.value='';render()}});render();
